version: '3.5'
services:
  client:
    image: harsh2835/finance-tracker-client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    image: harsh2835/finance-tracker-server
    ports:
      - "4000:4000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /home/harsh2835/Downloads/FinMate-DevOps-main/data/db:/data/db